version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_eclock
    environment:
      POSTGRES_USER: eclock_user
      POSTGRES_PASSWORD: eclock@pass
      POSTGRES_DB: eclock_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent volume for PostgreSQL data

    ports:
      - "5432:5432"                     # Expose PostgreSQL port
    restart: always                     # Restart policy
volumes:
  postgres_data: