spring:
  application:
    name: eclock

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:eclock_db
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console







